### ISSUE TITLE
https://api-watcher.rinkeby.omgx.network/ should return list of all contracts deployed

### ISSUE THREAD

**Issue by CAPtheorem** [omgnetwork/optimism#213]
Right now, `https://api-watcher.rinkeby.omgx.network/` returns events such as deposits, exits, and transfers. To support deploying new ERC20s and NFTs on OMGX, it would be useful to have the api-watcher also return a list of contracts deployed by the calling `this.account`. That will make it easy to show a list of token- and NFT contracts owned by the user. 

suggestion - add new endpoint - e.g. 

```
).post('get.deployments', {
        address: this.account,
```

and have that return 

`const deployments = response.data`

where deployments is a list of contract addresses deployed by `this.account`

**Comment by cby3149** [comment]
Fixed
