### ISSUE TITLE
Wallet toDos

### ISSUE THREAD

**Issue by CAPtheorem** [omgnetwork/optimism#236]
Farm page - `Rename to Earn`
Farm page - Fix `Warning: Each child in a list should have a unique "key" prop.`
Overall - lookup current gasPrice and use that to populate the slow/normal/fast buttons for the modals - needed for main net
Overall - improved metadata for transactions; also add amounts transacted if possible

**Comment by sk-enya** [comment]
changes for lookup current gas price.
https://github.com/omgnetwork/optimism/pull/240

**Comment by CAPtheorem** [comment]
Resolved
