### ISSUE TITLE
Gateway UI - DAO screen, proposal listing 

### ISSUE THREAD

**Issue by CAPtheorem** [omgnetwork/optimism#356]
Suggest to change to the usual multipage view - there could be 100 proposals, and so will be very tedious to have to scroll up and down to find the right one.
<img width="950" alt="Screen Shot 2021-09-07 at 8 42 40 AM" src="https://user-images.githubusercontent.com/79423264/132373494-c1c15601-18b3-4f81-9250-4a5aeff30e63.png">

**Comment by sk-enya** [comment]
added the pagination on proposal with 3 proposal per page so we can have better view.
changes are available into the PR

https://github.com/omgnetwork/optimism/pull/354
