### ISSUE TITLE
Gateway UI - DAO

### ISSUE THREAD

**Issue by CAPtheorem** [omgnetwork/optimism#358]
The DAO will only be on L2, so:

1/ Do not try to query non-existent contracts on L1, in networkServices.js
2. When people are on L1, and go to the DAO page, just show a simple message that says: `To use the Boba DAO, you must be on L2. To change layers, click HERE`.

**Comment by sk-enya** [comment]
changes done and push to the PR
https://github.com/omgnetwork/optimism/pull/354
