### ISSUE TITLE
Text upon fast withdrawal disappears below 'switch layer' button

### ISSUE THREAD

**Issue by maxglaser87** [omgnetwork/optimism#371]
when metamask is set to L1 and user clicks on fast withdrawal, the text to set metamask to L2 disappears half way under 'switch layer' button. consider shorting to 'switch to L2'
![image](https://user-images.githubusercontent.com/62317811/132618369-339e3b71-4311-44b3-81cf-d11ee0dcdbb5.png)

**Comment by maxglaser87** [comment]
Same goes for when L2 is active and user is prompted to switch to L1

**Comment by sk-enya** [comment]
Done! 
![Screenshot 2021-09-09 at 8 15 10 PM](https://user-images.githubusercontent.com/86316370/132707635-7860f121-54d6-41f8-8a3f-2226fe7a2c95.png)

**Comment by sk-enya** [comment]
Changes done and merge into the develop branch.
