### ISSUE TITLE
DAO - user can submit proposal without gov tokens (tx fails)

### ISSUE THREAD

**Issue by maxglaser87** [omgnetwork/optimism#372]
should prompt users to transfer gov tokens first if balance == 0

https://blockexplorer.rinkeby.boba.network/tx/0xd9a27d760e548bce5ef2dcf3fbdbaeb04705e38cd6183157e968ce0009d8f382/token-transfers

**Comment by sk-enya** [comment]
Are you referring to this balance?

![Screenshot 2021-09-09 at 8 17 43 PM](https://user-images.githubusercontent.com/86316370/132708118-446e26f5-45b7-4594-b6c9-1456f17f6f9e.png)

**Comment by sk-enya** [comment]
@CAPtheorem 
Can you please help me with verbiage for the alert / modal to show in case of create proposal if user don't have balance

**Comment by sk-enya** [comment]
I am looking into this bug.

**Comment by sk-enya** [comment]
Changes done !
![Screenshot 2021-09-10 at 2 29 18 AM](https://user-images.githubusercontent.com/86316370/132761844-797dcf38-34f8-4c06-92fa-c570afd5e742.png)

**Comment by sk-enya** [comment]
https://github.com/omgnetwork/optimism/pull/391

**Comment by CAPtheorem** [comment]
Fixed
