### ISSUE TITLE
Gateway network switch bug

### ISSUE THREAD

**Issue by cby3149** [omgnetwork/optimism#373]
When I was on Mainnet, I picked the rinkeby network. I saw the `wrong network` module, so I closed the module. The top right network was updated to rinkeby. However, I was still on Mainnet.
<img width="333" alt="image" src="https://user-images.githubusercontent.com/46272347/132619643-2dbc9138-3e80-4810-9eca-130cf64de80e.png">

**Comment by MitchellUnknown** [comment]
When you use this bug, it's good to know that the little switch pop up won't close! Only after you refresh the page, but then you have to reconnect metamask for a second time. 

![image](https://user-images.githubusercontent.com/90399189/132732501-7b1c31ee-406c-43bd-88e3-7aee7b48290a.png)

**Comment by MitchellUnknown** [comment]
Extra info: When you do close the 'wrong network module' and did not switch your network in metamask. The network switcher in the left corner will not respond to any user input afterwords. Only if you refresh the page.

**Comment by CAPtheorem** [comment]
This button will be removed soon, since each network will have their own gateway (e.g. gateway.boba.network and gateway.rinkeby.boba, so no need to switch networks
