### ISSUE TITLE
BOBA Gateway - close modals not working

### ISSUE THREAD

**Issue by LubosVoska** [omgnetwork/optimism#374]
In DAO page modals x buttons is not working (Transfer and Delegate votes).

![image](https://user-images.githubusercontent.com/16544878/132627679-98a3d257-db81-4b68-bd4e-d46fed75d79f.png)

![image](https://user-images.githubusercontent.com/16544878/132627502-4c18703f-0dce-4ec9-a0b1-6a3819002a94.png)

**Comment by sk-enya** [comment]
Changes are done!

**Comment by sk-enya** [comment]
Changes as has been merge into the develop branch

@LubosVoska  please validate on close the issue once tested.
