### ISSUE TITLE
Boba Gateway - Bug Rejection Metamask (Rinkeby) 

### ISSUE THREAD

**Issue by MitchellUnknown** [omgnetwork/optimism#377]
When you want/need to approve an action on metamask and decide to reject/cancel it, the Boba gateway will show you a green indication: transaction submitted. Should be a red indication: transaction/action rejected or cancelled.
![Bug Reject Metamask Action](https://user-images.githubusercontent.com/90399189/132701754-b9cd29b5-77dd-44d6-82fd-073c8d2452b9.png)

**Comment by CAPtheorem** [comment]
@sk-enya Basically, need to look for MetaMask return and need to handle that correctly.

**Comment by sk-enya** [comment]
@CAPtheorem looks like you have already fix this issue.

![Screenshot 2021-09-13 at 1 44 55 AM](https://user-images.githubusercontent.com/86316370/133001542-148f18ff-733a-42ba-8354-6087c40534eb.png)

**Comment by sk-enya** [comment]
Please let me know if anythings needs to be done apart from this.

**Comment by MitchellUnknown** [comment]
@CAPtheorem @sk-enya 
When you deposit funds with the slow option, it still gives the green ETH was submitted message. The fast deposit option gives the right error message.

![image](https://user-images.githubusercontent.com/90399189/133940139-55eebac5-1b2f-4aad-9173-d8ba24c0c46a.png)

**Comment by sk-enya** [comment]
Looks good changes are available on develop branch already.
