### ISSUE TITLE
Boba Gateway - Feature Earn Tab (Rinkeby)

### ISSUE THREAD

**Issue by MitchellUnknown** [omgnetwork/optimism#378]
Maybe it's easy to make an extra tab, where you can see in one glance what your earnings are, which coins you can farm, and coins that you are currenlty lending out to provide liquidity. Or if you don't choose to make an extra tab, I suggest to make some kind of filter/buttons with:  

[ ] Only show coins that you are currently lending out to provide liquidity. 
[ ] Only show current outstanding earnings

![Feature Earning](https://user-images.githubusercontent.com/90399189/132707527-28c25dc5-7356-4185-bde0-0a2a89148475.png)

**Comment by CAPtheorem** [comment]
This is a really good idea. @sk-enya - the best way to do this is have a little checkbox that says `Show all?`. For the page default, please only show pools where the account has a non-zero share, but if you click `show all` it shows all LPs, just like we do now. Other approaches for doing this would drive too many code changes, so lets start with the simple `Show all` checkbox

**Comment by sk-enya** [comment]
@CAPtheorem can you please help here?
What does mean by the share? 
do you mean to say the balance?

**Comment by sk-enya** [comment]
Added check box as mention.

![Screenshot 2021-09-12 at 1 32 14 PM](https://user-images.githubusercontent.com/86316370/132978886-e7c01def-6650-46b6-8b6a-a1fedde5eb66.png)

**Comment by sk-enya** [comment]
Looks good to me changes available on develop branch.

@CAPtheorem closing the issue

**Comment by HangingGolem** [comment]
@CAPtheorem 
Using the reverse logic here for no reason
Usually: do action -> smth (here: filter) applies
Ours now: do action -> filter removes 

Also then default state for newcomer will be checkbox unselected -> filter not applied

fyi. was a bit confused when saw this checkbox first time 
![image](https://user-images.githubusercontent.com/33980109/133087966-f1d47a3b-004a-4b6a-b9b3-fc3e9a5e471d.png)

**Comment by CAPtheorem** [comment]
@HangingGolem - great point - that logic should be flipped
