### ISSUE TITLE
Boba Gateway - Bug Network Switcher (Rinkeby)

### ISSUE THREAD

**Issue by MitchellUnknown** [omgnetwork/optimism#379]
When you are on the earn page and you press the 'switch network button" it switches the network correctly. However, it takes you back to the homescreen. Would love to stay on the earn page after the switch.

edit: It also happens when you use the network switcher in the left top corner. I think it lands on the wallet page by default. 

![Bug Switch Network Takes You Home](https://user-images.githubusercontent.com/90399189/132713215-6e91bde6-8e34-4aa0-84a7-b7233230293b.png)

**Comment by CAPtheorem** [comment]
Great catch - Was fixed in pending release by https://github.com/omgnetwork/optimism/pull/405
