### ISSUE TITLE
Boba Gateway - Transaction History L2 Hash (Rinkeby)

### ISSUE THREAD

**Issue by MitchellUnknown** [omgnetwork/optimism#385]
When you are on the 'transaction history page' and press the 'deposit' tab. You can see your deposit history from L1 > l2. But when you click on 'more information' the L2 hash is not a clickable event. The UI indicates that it is. It should redirect to the Boba blockexplorer with the correct L2 hash. Or a link that is clickable that directs you to the L2 block with that L2 deposit hash. 

![Bug Not clickable](https://user-images.githubusercontent.com/90399189/132722442-6ba66f49-477e-4dae-9b86-82ce55bda850.png)

**Comment by sk-enya** [comment]
@CAPtheorem 
Can you please help me with correct way of creating the link for this?

`txLink: chainLink({
                      chain: i.crossDomainMessage.chain,//"L1",
                      hash: i.crossDomainMessage.l1Hash
                    })`

**Comment by sk-enya** [comment]
changes done!

**Comment by sk-enya** [comment]
Looks good to me changes available on develop branch.

@CAPtheorem closing the issue
