### ISSUE TITLE
Boba Gateway - Close Network Switcher (Rinkeby)

### ISSUE THREAD

**Issue by MitchellUnknown** [omgnetwork/optimism#387]
When you change your mind of switching networks, the pop-up only has one option to close. Many users just want the pop-up to close, when they click randomly on the page. 

![image](https://user-images.githubusercontent.com/90399189/132736837-66c959b5-0857-42ca-bbc2-cd39d77498ca.png)

**Comment by CAPtheorem** [comment]
The network switcher will be (removed for most users) within the next few days - they will choose networks by choosing either `gateway.boba.network` or `gateway.rinkeby.boba.network` - this will simplify the user experience.
