### ISSUE TITLE
Boba Gateway : Alert Design is not matching with wallet 

### ISSUE THREAD

**Issue by sk-enya** [omgnetwork/optimism#388]
Current alert and error toast design is not matching with design so we can fix it out with design suggest from alext.

![Screenshot 2021-09-09 at 11 44 13 PM](https://user-images.githubusercontent.com/86316370/132740580-e2109d12-cc1e-437c-abc4-a5b609415d79.png)

With cross button instead of other buttons reffered screenshot below.
![Screenshot 2021-09-09 at 11 46 07 PM](https://user-images.githubusercontent.com/86316370/132740729-92532b7f-1aab-42cc-b2fc-0934b0ffc903.png)

**Comment by sk-enya** [comment]
@CAPtheorem please prioritise this one.

**Comment by CAPtheorem** [comment]
No action for now
