### ISSUE TITLE
The decimal place of USDC is wrong.

### ISSUE THREAD

**Issue by CAPtheorem** [omgnetwork/optimism#389]
The decimal place of USDC is wrong.
<img width="1135" alt="image" src="https://user-images.githubusercontent.com/46272347/132597448-3e516c2c-7942-4ac3-9a2e-b19025981ebf.png">

_Originally posted by @cby3149 in https://github.com/omgnetwork/optimism/issues/367#issuecomment-915633009_

**Comment by sk-enya** [comment]
https://github.com/omgnetwork/optimism/pull/391

changes has been available in above PR

**Comment by CAPtheorem** [comment]
Fixed
