### ISSUE TITLE
Boba Gateway - [Serious Glitch] Adding Liquidity to L2 pool & UX Bugs (Rinkeby)

### ISSUE THREAD

**Issue by MitchellUnknown** [omgnetwork/optimism#390]
1 **FIXED [Serious glitch]**

This is a pretty weird bug, can't really explain it in a simple way. So I am just logging what happend. It's about staking oETH on rinkeby. When you open the earn page on rinkeby and go to the l2 liquidity pool, you can stake your oETH. I already had 1 ether staked, so I clicked on the stake more button. But I encounterd a weird bug, that appears to happen after you succesfully add liquidity. When you want to add liquidity with the 'stake more buttton' a pop-up window. The first time you want to add liquidity the button shows '**stake**' and you can approve this action with metamask. After approving your staked amount in metamask you will get a notification on the boba gateway that '**Your liquidity was added**'. You will be redirected to the main wallet page (should be fixed to stay on the earn page). At this point when you go back to the earn page and repeat the same proces, things will bug out. When you press the same 'stake more button' this time a pop-up window appears with a different button '**approve amount**'. After you decide what amount you want to stake, metamask would pop up with a different message than the first time you added liquidity. When you approve the metamask data, you will get a notification from the boba gateway that the '**amount was approved**' but the liquidity was not added to the pool. And you have to pay for the transaction. If you don't leave the screen, you will end up in a loop. A loop where you end up paying a lot of fees for trying to add liquidity. When you exit the pop-up window and go back to the earn page, you can add liquidity again. But you will end up in the same loop after one succesful try. 

![Bug Add Liquidity Loop](https://user-images.githubusercontent.com/90399189/132758445-887e7ed0-00bd-4914-81b8-eabf35b107f9.png)

4 Different size 'pop-up menu buttons' when you want to add liquidity to the l2 pool after you press 'stake'..  

![Different style](https://user-images.githubusercontent.com/90399189/132758674-a1ec1427-7b74-4a96-9c4d-5814de300d19.png)

5. Mobile UX glitch, can't scroll through the warning of mainnet beta wallet.

![Foto 09-09-2021 22 39 00](https://user-images.githubusercontent.com/90399189/132759535-3098222a-06f9-4e34-9c20-7192d245d513.jpg)

**Comment by CAPtheorem** [comment]
working through this list now - all good catches

**Comment by CAPtheorem** [comment]
@sk-enya please tackle the add liquidity glitch since you just worked on the liquidity decimals bug.
@osnysantos please tackle 2, 4, and 5.

**Comment by MitchellUnknown** [comment]
@sk-enya Some extra details, maybe it will help you find the problem. 

- I remember that when you wanted to add liquidity on L2 on the old testnet UI you had to approve/sign **two transactions** with metamask. In the new interface when you get the button 'stake' you only have to approve/sign **one metamask** transaction before your liquidity is added. I think when you get the 'approve amount button' the user interface bugs out, because the user needs to get another metamask transaction to 'complete' the staking. 

![image](https://user-images.githubusercontent.com/90399189/132846307-e8a398d7-ec03-4587-8fc4-6dc4aeaec370.png)

![image](https://user-images.githubusercontent.com/90399189/132846819-02cf04ff-4bf3-4ad8-800d-f008c2650056.png)

**Comment by CAPtheorem** [comment]
Your key issue is addressed/fixed in the pending https://github.com/omgnetwork/optimism/pull/402. In terms of your other issues, I'll close this issue and refile all your others as separate issues, so we can keep better track of everything
