### ISSUE TITLE
Boba Gateway - Feature - DAO - Free form text proposal add html link

### ISSUE THREAD

**Issue by CAPtheorem** [omgnetwork/optimism#393]
Right now, when you propose a free form text proposal, you can only provide a very short description. Please add an input field for a URI, such that when loading the proposal, the URI can be displayed as a clickable link that leads people to more information. The URI can be packed into the description string, for example, by separating the description and the URI by @@ e.g. `Proposal to build an open source blockexplorer@@https://ipfs.io/ipfs/<CID>`

**Comment by sk-enya** [comment]
Changes done.
![Screenshot 2021-09-10 at 6 42 10 PM](https://user-images.githubusercontent.com/86316370/132858511-a218b182-f188-4fcc-8e24-4e90253960b5.png)
![Screenshot 2021-09-10 at 6 41 49 PM](https://user-images.githubusercontent.com/86316370/132858523-a98e91c2-e17f-435b-bfad-f8378a71b015.png)

**Comment by sk-enya** [comment]
Changes Are available here
https://github.com/omgnetwork/optimism/pull/396

**Comment by CAPtheorem** [comment]
Perfect
