### ISSUE TITLE
Boba Gateway - DAO Popup Menu Closing Button (Rinkeby)

### ISSUE THREAD

**Issue by MitchellUnknown** [omgnetwork/optimism#395]
The closing button does not work at the moment. You can close the menu with the 'cancel' button though. This is also the case for the delegate popup menu!

![image](https://user-images.githubusercontent.com/90399189/132854847-31f14810-545b-4c94-b08d-c383c4c01738.png)

**Comment by CAPtheorem** [comment]
Good find - fixing

**Comment by sk-enya** [comment]
Already fixed
