### ISSUE TITLE
Fast Exit allows for a negative value (to be filled in) to be exited

### ISSUE THREAD

**Issue by DaRealX** [omgnetwork/optimism#398]
Fast Exit allows for a negative value (to be filled in) to be exited.
![Fast Exit allows for a number below zero 10-09-2021](https://user-images.githubusercontent.com/80894290/132865954-8cd9ff24-048c-4eef-990b-f7e587f7f4ef.png)

**Comment by CAPtheorem** [comment]
Fixing!

**Comment by CAPtheorem** [comment]
Fixed in pending https://github.com/omgnetwork/optimism/pull/402. Thanks again!
