### ISSUE TITLE
Boba Gateway - Pending Transaction Logic Order (Rinkeby)

### ISSUE THREAD

**Issue by MitchellUnknown** [omgnetwork/optimism#413]
I noticed that when you have a pending traditional exit running and you want to start a (slow deposit, fast deposit or fast exit) this newer pending transaction will always show underneath the traditional exit, instead on top. If you have 3 pending traditional exits running, the user have to scroll to the second page to know the latest acitivy...

**[Potential solution]** 
I think I found where the problem lies. The UI is looking for the latest timestamp, based on the estimated completion time. But because the traditional exit takes 7 days, this will be always on top for the next 7 days. To fix this, it should be based on starting time!

![Boba Gateway - Pending Logic](https://user-images.githubusercontent.com/90399189/132943628-645543f5-7084-48e4-acb8-856a314e4002.png)

**Comment by CAPtheorem** [comment]
Good catch!

**Comment by sk-enya** [comment]
https://github.com/omgnetwork/optimism/pull/420

**Comment by CAPtheorem** [comment]
fixed
