### ISSUE TITLE
Boba Gateway - Connection Issues Reported by Users (White Screen of Death)

### ISSUE THREAD

**Issue by MitchellUnknown** [omgnetwork/optimism#418]
People who are trying to use the boba gateway _(gateway.boba.network)_ are reporting that they can't acces it, because they are getting a white screen of death. I think I was one of the first that run into this issue. I tried every possible solution I could think of, but I was unable to fix it.

**Solutions that didn't work:**
- Clear cache on Chrome
- Opening the gateway on different browsers (Brave, IE, Firefox)
- Opening the gateway on different devices (Mobile, Ipad)
- Driving to a friend and using his internet and his laptop. 
- Metamask Re-install 
- DNS chance 
- VPN 

**What we know about the issue:**
- It seems to effect most users located in Holland, but also people located in Denmark reported issues.
- When I open the gateway link through telegram with my phone, the gateway works. But when I try to open it manually with my phone's browser, it fails.
- Maybe a cloudflare proxy that is corrupt 
- Maybe a metamask update that gone bad 
- Maybe an Amazon cloud server error
- Maybe major code update from the boba team recently? (last 24-48 hours)

Here are some pictures from community members reporting the issue. At this point, we are clueless what the problem is. Because there are so many contradictory signs, it's hard to guess what the problem might be. 

![Laptop Browsers](https://user-images.githubusercontent.com/90399189/132959788-c23440f8-78d0-4337-a0b7-3c519d0b18a7.png)

![User 1](https://user-images.githubusercontent.com/90399189/132959793-561319cb-955e-473b-b466-092758df23ff.png)

![User 2](https://user-images.githubusercontent.com/90399189/132959800-8bda46cb-4a0b-4068-a1cc-9cc37250e5ab.png)

![photo_2021-09-11_15-10-57 (2)](https://user-images.githubusercontent.com/90399189/132959803-5ec607dc-957a-4f12-8b5a-4deb1f919198.jpg)

![Blanco](https://user-images.githubusercontent.com/90399189/132959805-55ad4c15-8adf-41ec-a34c-9e2079cdd79d.png)

**Comment by CAPtheorem** [comment]
Tested in Denmark, France, and Singapore on Chrome and Safari at 00:29 Sunday, September 12, 2021 Greenwich Mean Time (GMT) and could not reproduce problem. Showing good function across all those regions. 

*NOTE - since MetaMask is required, the only useful way to interact with the gateway on mobile is via the MetaMask browser. In the MetaMask app, select Hamburger, then Browser* 

But keep those reports coming in, since if it's not working for you, then that means there is a problem somewhere, even if it's not so easy to find.

**Comment by MitchellUnknown** [comment]
I think the issue is resolved, so you can close this one. Sorry for the spam lately in github. We as the community are extremely proud of the work you guys put in over the last 8 months. The gateway looks incredible! And we are excited to help, test and report any weird issue’s/bugs/glitches so it becomes robust for the next billion users on Ethereum. I know you guys are maxed out on workload. Anyhow, thanks for responding and testing this issue. Good luck, the coming weeks. 👍

**Comment by CAPtheorem** [comment]
Whew great - you are doing an amazing job! Keep those suggestions coming, please. We'll do everything we can to move quickly on them.
