### ISSUE TITLE
Boba gateway -  Dao PAGE SEEMS BROKEN

### ISSUE THREAD

**Issue by sk-enya** [omgnetwork/optimism#419]
1. There was crash on landing DAO 
2. Proposal list was not rendering correctly.
3. Create proposal for voting threshold was not working correctly check for the url not handled correctly.
4. Active proposal is not visible on UI showing blank strip @CAPtheorem can you please help me is this intentional or got removed in resolving conflict ?

**Comment by sk-enya** [comment]
fix for 1, 2, 3 is available at 
https://github.com/omgnetwork/optimism/pull/420

**Comment by CAPtheorem** [comment]
4. also resolved
