### ISSUE TITLE
Boba Gateway - Count down timer keeps running on traditional exit.

### ISSUE THREAD

**Issue by sk-enya** [omgnetwork/optimism#421]
I first did the fast exit which works correctly and got the data in the pending transaction list.

then click on **standard exit** but seems like exit button in disable with countdown timer and unable.

![Screenshot 2021-09-12 at 12 04 33 PM](https://user-images.githubusercontent.com/86316370/132975530-4d3522a7-1f21-4da0-b475-01c4aef8d36c.png)

**Comment by sk-enya** [comment]
After some time transaction seems to be get removed from the pending and button is again accessible.

So I guess we should block the user from click action buttons on listAccount itself.

**Comment by CAPtheorem** [comment]
fixed in https://github.com/omgnetwork/optimism/pull/496
