### ISSUE TITLE
Boba gateway - left align the main content

### ISSUE THREAD

**Issue by CAPtheorem** [omgnetwork/optimism#423]
Otherwise there is a black bar between the left menu and the content - please have the main connect stay next to the left menu bar
<img width="1886" alt="Skærmbillede 2021-09-12 kl  9 49 02 AM" src="https://user-images.githubusercontent.com/79423264/132995964-959f56c3-cf94-47c8-8c70-ba6f5d949400.png">

**Comment by sk-enya** [comment]
@CAPtheorem 
can you please help me with screensize to test this out?

**Comment by CAPtheorem** [comment]
tested; fixed in https://github.com/omgnetwork/optimism/pull/426
