### ISSUE TITLE
Gateway - DAO page, mobile - top field not responsive to mobile

### ISSUE THREAD

**Issue by CAPtheorem** [omgnetwork/optimism#428]
<img width="851" alt="Screen Shot 2021-09-12 at 11 52 25 AM" src="https://user-images.githubusercontent.com/79423264/132999368-24d7ee5b-ad73-4b74-ba76-a7caf971f641.png">

**Comment by sk-enya** [comment]
changes done and push 
![Uploading Screenshot 2021-09-13 at 12.57.51 AM.png…]()
