### ISSUE TITLE
Boba Gateway - Small Text Tweaks/Suggestions 

### ISSUE THREAD

**Issue by MitchellUnknown** [omgnetwork/optimism#431]
1. It would be nice, if you can add an indication that the APR in the earn page is a percentage. 

![Boba Gateway - Small Suggestions](https://user-images.githubusercontent.com/90399189/133006091-cd353e07-cd6c-46e0-853d-d9fc9a8aa242.png)

2. In the current design, the wallet page shows _L1 (mainnet)_, I think it's better to change it to something the next generation of people understand, and thats the name Ethereum. And the _(mainnet)_ text is not necessary imo, because Ethereum is already mainnet. And in the description at the wallet page you already explains that this is a mainnet beta. Same goes for the Boba network. And if you want to keep the _(mainnet)_ text, you should consider to chance it to _(mainnet beta)._ 

![Boba Gateway - Small Suggestions 2](https://user-images.githubusercontent.com/90399189/133006305-5d1b6170-2fd7-4d1b-acee-3827a3b2d570.png)

**Comment by CAPtheorem** [comment]
Resolved in pending PR https://github.com/omgnetwork/optimism/pull/434
