### ISSUE TITLE
Boba Gateway - History page on mobile seems broken with styling.

### ISSUE THREAD

**Issue by sk-enya** [omgnetwork/optimism#437]
![Screenshot 2021-09-13 at 11 29 35 PM](https://user-images.githubusercontent.com/86316370/133133721-05877c6d-b13d-4729-8e79-7f640986dea4.png)

**Comment by HangingGolem** [comment]
@osnysantos 

Smth like this, as long as search is on a separate row, and we shorten text around date picker we're good.
![image](https://user-images.githubusercontent.com/33980109/133282328-0bab8409-ad88-4a0c-95a1-57caeddee69b.png)

For the info in the table itself, just make sure that block number doesn't affect the whole row. Let's group it with main title and move to top right on the card.
![image](https://user-images.githubusercontent.com/33980109/133282934-2309a76a-b5a8-4779-8fa3-ae0777908db9.png)
![image](https://user-images.githubusercontent.com/33980109/133282949-0a26a3f6-3219-45e2-b1d6-3a7b63f2d40b.png)
