### ISSUE TITLE
Boba Gateway - Augur Listed as Reputation on Earn Page

### ISSUE THREAD

**Issue by jwboba** [omgnetwork/optimism#454]
Augur is listed as Reputation on the Earn Page, and is showing the ETH logo.

![image](https://user-images.githubusercontent.com/90710496/133346288-208f3ebc-bf29-4132-8360-56cf5a45466c.png)

**Comment by sk-enya** [comment]
Okay will check @CAPtheorem can we use this one as logo?
![augur](https://user-images.githubusercontent.com/86316370/133471688-0aa50148-1c0d-4245-afb0-e5d773404d2f.png)

**Comment by CAPtheorem** [comment]
Yes, go for it @sk-enya (re. Icon etc.).

**Comment by CAPtheorem** [comment]
We currently only support Augur version 2, i.e. REPv2 at `0x221657776846890989a759ba2973e427dff5c9bb`. If there is community demand for a REP bridge, can add that too. Yes/no @jwboba?

**Comment by CAPtheorem** [comment]
System checked for REPv2 support - all checks pass.
<img width="219" alt="Screen Shot 2021-09-17 at 12 56 45 PM" src="https://user-images.githubusercontent.com/79423264/133846880-bc811bc1-6acf-4e3f-a2b3-539b47650af1.png">

**Comment by CAPtheorem** [comment]
Fixed in pending gateway update
