### ISSUE TITLE
Boba Gateway - Improve UX when switching Chains

### ISSUE THREAD

**Issue by lt-hash** [omgnetwork/optimism#477]
When the Metamask button is clicked, I get the following message:
![image](https://user-images.githubusercontent.com/73152893/133935405-51567770-df87-4c6c-ab5c-c9c1307b98f2.png)

It should be either like pancake (pancakeswap.finance) and automatically offer to switch, or be like Trader Joe (traderjoexyz.com) and give a notice before sending a message to metamask to switch

![image](https://user-images.githubusercontent.com/73152893/133935430-76d09e8f-f535-4a8a-9dfb-809a2cfde3f6.png)
![image](https://user-images.githubusercontent.com/73152893/133935441-128ed699-c84a-4298-814e-73877950060e.png)
![image](https://user-images.githubusercontent.com/73152893/133935444-4b7865c4-3fe4-480e-9e88-e64a637bf361.png)

**Comment by CAPtheorem** [comment]
fixed
