### ISSUE TITLE
Boba Gateway - "Max" Amount

### ISSUE THREAD

**Issue by lt-hash** [omgnetwork/optimism#483]
When I click the number under "Max Available" I can't paste the Max Amount into the deposit amount field
![image](https://user-images.githubusercontent.com/73152893/133938060-cf5f5bac-54db-4d59-a92e-5b178d921c3a.png)

**Comment by lt-hash** [comment]
Another way of doing it:

![image](https://user-images.githubusercontent.com/73152893/133938149-f4301530-2a47-4353-b2f8-b35a2f041bff.png)

**Comment by CAPtheorem** [comment]
Addressed for nonETH ops in pending release (https://github.com/omgnetwork/optimism/pull/496)
