### ISSUE TITLE
UI text modification: Balance--> Available liquidity

### ISSUE THREAD

**Issue by 0xwinnie** [omgnetwork/optimism#489]
![image](https://user-images.githubusercontent.com/83700681/133960761-55faeeb3-18c2-47e3-aba7-9a1d7ea4ad26.png)
E.g
Liquidity (Available)
Total (Available)
Total liquidity (Available)

And
If you can have a description telling users that liquidity is for Bridge, it would be helpful.
![image](https://user-images.githubusercontent.com/83700681/133960852-a1c0f3a7-7a5f-456f-9e8b-03e65bcadcc8.png)

**Comment by sk-enya** [comment]
@CAPtheorem can you please comment on this? shall proceed for this?

**Comment by CAPtheorem** [comment]
Addressed in https://github.com/omgnetwork/optimism/pull/552
