### ISSUE TITLE
Boba Gateway - Unable to bridge using a hardware wallet with MetaMask

### ISSUE THREAD

**Issue by Oc3anWav3** [omgnetwork/optimism#498]
When you try to bridge to L2 using a hardware wallet with MetaMask, the transaction fails. Gamedazed on Discord tried to find the issue. He tried on Windows and Linux, Firefox and Chrome, hardware wallet and software (metamask generated) wallet. The common denominator between errors was the hardware wallet - he did not receive it outside of a hardware wallet. There are a number of comments on Discord about this.

**Comment by gamedazed** [comment]
I believe this is being caused by a CORS issue, it takes quite a while to get the error (or any exceptions) in debug, but I just caught this one

```
XHRGEThttps://api.etherscan.io/api?module=account&action=txlist&startblock=0&endblock=99999999&sort=asc&apikey=N4GKIV4TT1BP7UHC3VEJVJW2U6U6RWJ1ST/&address=<myAddress>
CORS Missing Allow Origin

	
GET
	https://api.etherscan.io/api?module=account&action=txlist&startblock=0&endblock=99999999&sort=asc&apikey=N4GKIV4TT1BP7UHC3VEJVJW2U6U6RWJ1ST/&address=<myAddress>
Status502
Bad Gateway
VersionHTTP/2
Transferred310 B (166 B size)
Referrer Policystrict-origin-when-cross-origin

    	
    content-length
    	166
    content-type
    	text/html
    date
    	Mon, 20 Sep 2021 23:23:54 GMT
    server
    	nginx
    X-Firefox-Spdy
    	h2
    	
    Accept
    	application/json
    Accept-Encoding
    	gzip, deflate, br
    Accept-Language
    	en-US,en;q=0.5
    Connection
    	keep-alive
    Host
    	api.etherscan.io
    Origin
    	https://gateway.boba.network
    Referer
    	https://gateway.boba.network/
    Sec-Fetch-Dest
    	empty
    Sec-Fetch-Mode
    	cors
    Sec-Fetch-Site
    	cross-site
    TE
    	trailers
    User-Agent
    	Mozilla/5.0 (X11; Linux x86_64; rv:90.0) Gecko/20100101 Firefox/90.0
```
``` 
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://api.etherscan.io/api?module=account&action=txlist&startblock=0&endblock=99999999&sort=asc&apikey=N4GKIV4TT1BP7UHC3VEJVJW2U6U6RWJ1ST/&address=<myAddress>. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing).
```

I noticed that while in spend approval submission the blockhash is never relayed to the metamask client, and as you would expect, never broadcasted. Essentially it requires a timeout from the backend web request to trigger the error

**Comment by bobachad** [comment]
@gamedazed I was able to bridge to Boba L2 with a ledger using Metamask. Can you double check Ledger is the latest fw, Metamask latest update and that contract calls are allowed again after fw update

**Comment by gamedazed** [comment]
You nailed it BobaChad! I was on v1.7.0, upgraded to v2.0.0 and contract interaction is a go!

**Comment by CAPtheorem** [comment]
EXCELLENT - WELL DONE. Yay! Will add to documentation in the gateway.

Update - fix added to documentation. 

https://github.com/omgnetwork/optimism/pull/496/commits/1c792e3c2c5cb4b34c3c4ad5f120d68393209562
