### ISSUE TITLE
Boba Gateway - The input number is invalid

### ISSUE THREAD

**Issue by cby3149** [omgnetwork/optimism#499]
* 3 doesn't work
<img width="793" alt="image" src="https://user-images.githubusercontent.com/46272347/134131558-39678cc1-28fd-4d99-b1d1-847ff1f4251b.png">
* 4 can't work 
<img width="764" alt="image" src="https://user-images.githubusercontent.com/46272347/134131634-9778d18b-8dfd-4e63-a8a2-f4f10ffdeffe.png">
* 20 can work
<img width="771" alt="image" src="https://user-images.githubusercontent.com/46272347/134131606-48321298-0e25-4503-85b8-c2837272564f.png">

**Comment by bobachad** [comment]
when I go straight to 'earn' and stake my OMG, tx approval comes up, tx approves, however after nothing happens and I can choose to approve again. https://etherscan.io/tx/0x919c42bcf8a3aaef69ac3b17f4927936b352e4e98ca62832f6d1cf57af7c0285

**Comment by CAPtheorem** [comment]
Fixed in pending release (https://github.com/omgnetwork/optimism/pull/496)
