### ISSUE TITLE
Boba Gateway Earn/Farm - No tx after approval of OMG 

### ISSUE THREAD

**Issue by bobachad** [omgnetwork/optimism#500]
when I go straight to L1 'earn' and stake my OMG, tx approval comes up, tx approves, however after nothing happens and I can choose to approve again. https://etherscan.io/tx/0x919c42bcf8a3aaef69ac3b17f4927936b352e4e98ca62832f6d1cf57af7c0285

**Comment by CAPtheorem** [comment]
Yes, fixing today.

**Comment by CAPtheorem** [comment]
Fixing in https://github.com/omgnetwork/optimism/pull/515 - will be live within a few hours.
