### ISSUE TITLE
Gateway OMG yield farming harvesting -> disable harvest button when earnings are still zero

### ISSUE THREAD

**Issue by CAPtheorem** [omgnetwork/optimism#504]
otherwise people could potentially burn gas on a zero value harvest call

**Comment by sk-enya** [comment]
seems issues with truncate on represenation of value on farm listing.


![Screenshot 2021-09-22 at 1 48 58 AM](https://user-images.githubusercontent.com/86316370/134241716-13b860c0-7ef0-4c07-bf7c-576b32e24994.png)

**Comment by sk-enya** [comment]
will be close in this.
https://github.com/omgnetwork/optimism/pull/496

**Comment by CAPtheorem** [comment]
yes, fixed
