### ISSUE TITLE
Gateway Feature - Add Amount On Pending Transaction 

### ISSUE THREAD

**Issue by MitchellUnknown** [omgnetwork/optimism#512]
When you bridge your funds, you will get a pending transaction with a lot of details. But I think the most important data is missing at first glance. And that is the amount you are bridging. I know you can click on the 'details' button and see the amount in the explorer. But thats an extra step for the user. I would love to see an amount on the pending transaction. 

![image](https://user-images.githubusercontent.com/90399189/134302195-aac86c9d-a3bf-4f23-9863-9d0355ac2321.png)

**Comment by CAPtheorem** [comment]
great idea - the amount information is currently not in the api-watcher payload, but could and should be.

**Comment by CAPtheorem** [comment]
@sk-enya FYI the watcher-api already trues the amount, so the only thing to do is to display that information in the pending and in the history:

See `response.action.amount` 

https://github.com/omgnetwork/optimism/tree/develop/ops_omgx/api/watcher-api

So, please, where possible, display this value to the user, per the @MitchellUnknown 's screenshot above. 

You will have to:

1/ get the value of `response.action.amount`
2/ convert it to the correct representation, suggest toFixed(2)
3/ get the token, and display the token too, ending up with `1.00 ETH` (for example)
