### ISSUE TITLE
Gateway Improvement - Date Picker Tweaks

### ISSUE THREAD

**Issue by MitchellUnknown** [omgnetwork/optimism#517]
**Date Picker Improvements**

_1. Invalid date range_
With the date picker on the gateway, you're able to search for an invalid date range. i.e there's no restriction to search in backwards, so I could do 22/09/2021 start date, 21/09/2021 end date which doesn't make sense. There's a good library for react called react hook form which you can wrap the datepicker in a controller and have a min/max attribute that will disable the date, it's also easy to include validation using that library via their hooks. Might make the devs life a lot easier.

![image](https://user-images.githubusercontent.com/90399189/134393019-36bc73eb-2172-4e0f-a05a-1fa93f1bac49.png)

2. Hover effect solid white
Currently when choosing a date via the date picker on the TX history page, the hover effect is a solid white box which obfuscates the date you're picking. Instead, you could change the hover to have a border, I also changed the date colour to be congruent with the lime. I understand that the orange was due to the MetaMask fox being directly above it? Anyway, that's what the difference would look like. 

![image](https://user-images.githubusercontent.com/90399189/134393088-939de045-fe92-4ec3-8d14-f1e6aaee2ae1.png)
![image](https://user-images.githubusercontent.com/90399189/134393368-e07b2734-0b6c-4bce-944c-1ccc50b89ebe.png)

Credits: Kally95

**Comment by CAPtheorem** [comment]
fixing now

**Comment by sk-enya** [comment]
changes done.

please review.
![Screenshot 2021-09-24 at 12 12 12 AM](https://user-images.githubusercontent.com/86316370/134565350-376a2dbb-1e79-4445-b730-91a70cb4aed2.png)
![Screenshot 2021-09-24 at 12 12 24 AM](https://user-images.githubusercontent.com/86316370/134565358-7539be21-9797-4d1a-9fb1-c2b276c211fd.png)

**Comment by CAPtheorem** [comment]
Fixed
