### ISSUE TITLE
Gateway Improvement - Consistency With Naming Bridge/Deposit/Exit

### ISSUE THREAD

**Issue by MitchellUnknown** [omgnetwork/optimism#521]
At some places you still get the text deposit/exit instead of bridging. I personally like the exit and deposit text better, because thats what regular people are used to. Nonetheless, it needs more consistency across the board. 

![Gateway Improvement - Different Names For Bridge Deposit Exit](https://user-images.githubusercontent.com/90399189/134466040-a594fce1-2268-4d74-8a86-623e9eb68c3e.png)

**Comment by CAPtheorem** [comment]
Good catch - will be addressed/pushed to production in less than 1 hour.

**Comment by CAPtheorem** [comment]
added to gateway - deployed - live.
