### ISSUE TITLE
Gateway - L1 > L2 ETH normal bridge gas error

### ISSUE THREAD

**Issue by Shaners42** [omgnetwork/optimism#522]
- Tried to bridge L1 ETH to L2 using normal bridge
- Have ~0.45 ETH and tried ~0.01 ETH deposit
- Shows generic red "failed to bridge error" with no Metamask popup
- F12 browser and the error message shows 
![image](https://user-images.githubusercontent.com/23640006/134501437-166e555d-633e-42f1-a7c4-c9077ea762d7.png)

- Fast entry appears to be fine

**Comment by CAPtheorem** [comment]
Good Cath, will be fixed in pending gateway update.

**Comment by CAPtheorem** [comment]
fixed - deployed - live.
