### ISSUE TITLE
Gateway Improvement - My Deposit Only Filter Issue (Earn page)

### ISSUE THREAD

**Issue by MitchellUnknown** [omgnetwork/optimism#524]
When you switch on the **_my deposits only_** filter you will get every token that is providing liquidity, instead of showing you only the tokens, in which you are providing liquidity

![Gateway - Earn My Deposits Only Filter Issue](https://user-images.githubusercontent.com/90399189/134518115-8a2d5266-db77-4fa8-947b-2c00863fc578.png)
.

**Comment by CAPtheorem** [comment]
The 'My Deposits Only' refers to all tokens in your wallet, not to the pools in which you are providing liquidity. We could add another checkbox 'My stakes Only' which would show only the pools for which you are proving liquidity. Would that be useful?

**Comment by MitchellUnknown** [comment]
> The 'My Deposits Only' refers to all tokens in your wallet, not to the pools in which you are providing liquidity. We could add another checkbox 'My stakes Only' which would show only the pools for which you are proving liquidity. Would that be useful?

It would be nice to only see your staked coins, but at this point i don’t think thats a real priority compared to the workload you guys are having at the moment. So maybe put this on the bottom on the to do list. I think the text ‘My Deposits Only’ text for now is a bit confusing. It suggest that the filter will only show my staked coins, at least that was my first thought when i pressed the checkmark.

**Comment by jwboba** [comment]
Maybe it should be "Owned Assets Only" as well as a "Staked Assets Only".

Also, currently when I clicked on "My Deposits Only", it shows all assets that have liquidity in them. I currently don't have any assets bridged so it might be different once I do, but it should be none.

![image](https://user-images.githubusercontent.com/90710496/134559954-c29dae62-80a0-4f12-84c7-3b0e5c22ff74.png)

**Comment by MitchellUnknown** [comment]
I am always the kind of guy that likes things super simple, and intuitive. My first thought when entering the earn page and I see a long list of coins, where are the buttons/filters that will lead to my staked coins or my outstanding earnings? I dont know if thats possible to implement, but this is me just thinking out loud as a user. 

**[ x ]** Show my staking  OR **[ x ]** Hide zero balances
**[ x ]** Show my earnings

**Comment by EpicChicken** [comment]
I'm also seeing all tokens with liquidity whether I own any or not. I'm using a new MEW wallet that has only ever had ETH and OMG on it. I have both staked on L2. When I check the 'My Deposits Only' box I still see Tether, DAI, USD, and SUSHI even though I've never had any of those in my wallet.

**Comment by CAPtheorem** [comment]
"Show my stakes" filtering will be added today

**Comment by CAPtheorem** [comment]
Fixed in https://github.com/omgnetwork/optimism/pull/552
