### ISSUE TITLE
Transaction Activity Data Does Not Show Up in MetaMask for Recipients

### ISSUE THREAD

**Issue by Oc3anWav3** [omgnetwork/optimism#534]
I received a transaction from another Boba Network user. The transaction worked well and I could see the oETH in MetaMask, but there was no information on the transaction under "Activity" in MM. I had to go to the blockexplorer to find the sender's address, then sent the oETH back. The sending data did appear under "Activity".

Also, the Gateway never showed the .04 that I received, although it appeared in MM. It may have appeared if I waited longer.

**Comment by Oc3anWav3** [comment]
Just realized that data may never appear in MM for recipients. If so, please go ahead and close this. Thanks!

**Comment by CAPtheorem** [comment]
Yes, these data never appear in MM for recipients
