### ISSUE TITLE
Cannot Stake OMG on L1

### ISSUE THREAD

**Issue by shopdropbeta** [omgnetwork/optimism#539]
I have approved the OMG tokens to stake which successfully executed.  I then tried to actually stake and keep on getting debited the fee for the transaction and the tokens never get staked.  The coins are approved (twice) but I can no longer do anything other than repeat the process to approve (and get charged a fee again).  I don't care about staking anymore, I just want to send the tokens back to a wallet but I cant.  It shows that I have OMG in the account but I am not able to select any to send, the max and send buttons are greyed out after typing a value (13).  It is like the tokens are locked up but I have no idea how to get access to them back?

Please see the attached screen shots.

Link to successful approval: https://etherscan.io/tx/0xd0b0fbf1d72cc18628d8cad06cd4e3c32c3765d15a829ed6db5b3a3a0ada1c0b

How can I reverse this approval and get access to my tokens to send back to a wallet?
![OMG Cannot Send Tokens](https://user-images.githubusercontent.com/58427689/135176534-02cfaf7f-bf0c-45ad-b991-ce4ded24b171.PNG)
![OMG already appoved](https://user-images.githubusercontent.com/58427689/135176536-a292af66-c3e2-4d6f-bcd8-bb2bdbe17d6d.PNG)
![OMG approval 1](https://user-images.githubusercontent.com/58427689/135176537-123d43f4-fd9f-4ba8-9659-ca1a863eb2b3.PNG)
![OMG approval fee](https://user-images.githubusercontent.com/58427689/135176539-be866a68-9ba7-4db9-8c57-c239e964e92f.PNG)
![OMG approval history TWICE](https://user-images.githubusercontent.com/58427689/135176540-3017d2ed-c996-4e72-a62b-15df0d5083be.PNG)

**Comment by CAPtheorem** [comment]
Hi @shopdropbeta - If the deposit into the LP did not take place, for whatever reason, then the OMG will still be in your wallet (which it looks like they are, based on your screen grab and also Etherscan). The approval does not change anything about the tokens, it simply allow other contracts to move those tokens for you. 

In your case, your deposit failed because your gas limit was too low (per https://etherscan.io/tx/0x67812853b5c01101e5f5a9d82d2a5fe93a412f855b0df23c4af8e48ad51164d1).

Looking more closely at the situation, (1) the OMG never left your wallet but (2) your wallet's ETH balance of 0.001 ETH is too low for you to transact on L1, which might be why MetaMask is greying out certain buttons.

**Comment by shopdropbeta** [comment]
Hi @CAPtheorem, thanks for the speedy response.  My ETH balance wasn't that low to begin with, I have lost fees executing transactions that didn't succeed.  Are you saying that if I top up some ETH that I will be able to send the OMG to a wallet (or go through the process again and stake the tokens albeit increasing the gas fee this time around?  This was just a test, I was going to stake all my OMG here but I am not sure I have the confidence to do it (sorry, I am not exactly Mr Technical).
Thanks again

**Comment by CAPtheorem** [comment]
Yes, precisely you are correct (_Quote: Are you saying that if I top up some ETH that I will be able to send the OMG to a wallet_). As an example, when I just staked some ERC20 tokens for test purposes, the L1 cost for the approval was 0.005 ETH, and the cost to stake was 0.01 ETH (0.005 + 0.01 = 0.015 ETH). That's expensive - unfortunately L1 operations are very expensive these days!

**Comment by shopdropbeta** [comment]
Tell me about it!  Ok, I will try again and see how it goes.  Thank you very much

**Comment by CAPtheorem** [comment]
In case you are having persistent problems with MetaMask, some people like to occasionally reset their MetaMask (MetaMask>Settings>Advanced>Reset Account).

**Comment by CAPtheorem** [comment]
Yes please keep me posted about how things go - we are here to help!

**Comment by CAPtheorem** [comment]
Seems like this has been resolved?

**Comment by shopdropbeta** [comment]
Sorry, yes, resolved!  Thank you very much
