### ISSUE TITLE
JSON response error and Network Error popups on 'Earn' page

### ISSUE THREAD

**Issue by EpicChicken** [omgnetwork/optimism#553]
I've been getting this popup error (first screenshot) intermittently throughout the day while leaving the 'Earn' page open in a Chrome tab. Seems to happen after I leave the page open for a while. I also noticed that the token list will sometimes take a long time to load if I refresh the page. Pretty sure it eventually timed out and gave up on loading the token list once or twice. I assumed the slowness was from increased use after the airdrop info was announced, so maybe the error is as well.

First screenshot is the error displayed on the Earn page itself, second screenshot are two errors displayed in the Chrome console. I looked back through the console logs and those two error messages were the only ones there for that particular browsing session. The black bars on both screenshots are from me trying to obscure my wallet address. 

![image](https://user-images.githubusercontent.com/91504062/135715939-be2a7c69-b182-4f36-a7b0-cd6f8ba390da.png)

![image](https://user-images.githubusercontent.com/91504062/135716097-f2d6826c-43b2-4fd8-a191-0fc9574cab49.png)

**Comment by EpicChicken** [comment]
Got a different 'Network Error' error message right after I submitted the issue. Similar to the other error, I had just left the 'Earn' page open for a few minutes while I submitted the original issue and the error was there when I switched back to that tab in Chrome.

![image](https://user-images.githubusercontent.com/91504062/135716740-70905af9-6ec7-4619-9781-773f0bac8bc2.png)

![image](https://user-images.githubusercontent.com/91504062/135716816-587e1653-7af0-4a4c-be6f-de06f28e25cb.png)

**Comment by CAPtheorem** [comment]
Looking now - thanks for the report.

**Comment by CAPtheorem** [comment]
Those are generally spurious and can be safely closed - basically, short dropouts of your internet. We'll filter them out.

**Comment by CAPtheorem** [comment]
Partially addressed in https://github.com/omgnetwork/optimism/pull/552
