### ISSUE TITLE
cant withdraw omg from boba layer 2

### ISSUE THREAD

**Issue by Chambers-Chambers** [omgnetwork/optimism#557]
ive attempted to send my omg back to layer one so i could trade it on another platform. but it has been stuck on pending even though the transaction was confirmed. tx hash 0x844f6e9833124349ba290be078d50a8f4ca4dcb5e7824e9df4b4f5a19fa69b79

**Comment by CAPtheorem** [comment]
Looks like this was a Fast Bridge; all looks good from here. More info soon.

**Comment by CAPtheorem** [comment]
As best as we can tell, the funds are in your L1 wallet (https://etherscan.io/tx/0x34c5e4766932a5d02b4276b69cb115716a905a5fc09ccedcf9ad66dd074245ef)
Let us know if this is not the case.
