### ISSUE TITLE
NFT page doesn’t allow removal of faulty address

### ISSUE THREAD

**Issue by Claude-Mon** [omgnetwork/optimism#603]
I made a mistake by adding BDoge contract address on the NFT page of the gateway. 

The shown error keeps on popping up and I can’t find a way to delete and correct this.

![4239BFF9-1857-479C-A716-E8093337395A](https://user-images.githubusercontent.com/93547358/144278856-2ac90d54-1591-4015-b117-e066b5f3efc5.jpeg)
![384ACC7A-BF77-4665-A25A-DE69821C47D9](https://user-images.githubusercontent.com/93547358/144278882-946dc8c9-4fde-418f-9eec-a412ab6edb0a.jpeg)

**Comment by Claude-Mon** [comment]
This message refreshes every 10 seconds in console 
![Uploading 8860A438-C6B1-4EA4-A87C-FACB3D2205F4.jpeg…]()

**Comment by Claude-Mon** [comment]
![Uploading CCAA85A8-ECFA-4D55-B0D8-425F1C14F4E3.jpeg…]()

**Comment by Claude-Mon** [comment]
This issue comes up on the edge browser. The bobagateway on google chrome doesn’t show this error,  neither the contract address.

**Comment by Kally95** [comment]
@Claude-Mon I believe I have the same issue with importing the BobaDoge NFT's. I'm on chrome and getting the error. Quite persistent. The issue I posted just under yours is regarding this issue too. Would be nice if we could remove imported addresses.

**Comment by Claude-Mon** [comment]
This problem has been fixed by doing the following: in edge browser, go to settings and reset. Also did I re-install metamask. After doing this, the NFT page has been restored and no message coming up anymore.

**Comment by Kally95** [comment]
Nice, that worked, thanks. I did a chrome reset and cleared cache. Have to re import my punks though so this is a temp fix. I'll include these details in my post and tag you.
